CREATE DATABASE LibraryManagementSystem

USE LibraryManagementSystem


CREATE TABLE [User] (
	Id INT IDENTITY,
	Username VARCHAR(50),
	[Password] VARCHAR(50),
	Name VARCHAR(50),
	Email VARCHAR(50),
	Salt VARCHAR(50)
);
insert into [User] (Username, [Password], Name, Email, Salt) values ('mlangabeer0', 'FJ007r', 'Melissa Langabeer', 'mlangabeer0@pbs.org', '9yHGUb4M6OPr');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ptraynor1', 'xdTAZUf8Ml1', 'Peria Traynor', 'ptraynor1@wikimedia.org', '3IGDTuEQayyQ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('jricciardo2', 'MjMbwhr', 'Joann Ricciardo', 'jricciardo2@bbc.co.uk', 'luG6k08WA3');
insert into [User] (Username, [Password], Name, Email, Salt) values ('tcucuzza3', 'oKAURP4wVS6', 'Tad Cucuzza', 'tcucuzza3@goodreads.com', 'BX57bZYHu');
insert into [User] (Username, [Password], Name, Email, Salt) values ('tcallow4', 'go9Mn5', 'Tanner Callow', 'tcallow4@clickbank.net', 'av5wFPIktoFU');
insert into [User] (Username, [Password], Name, Email, Salt) values ('tgaucher5', 'EEQ9EwuGqwc', 'Tomaso Gaucher', 'tgaucher5@china.com.cn', '3ie4eZ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('pbeeby6', 'fTttdP7E14', 'Payton Beeby', 'pbeeby6@rakuten.co.jp', 'CrEcQSsZ4HSV');
insert into [User] (Username, [Password], Name, Email, Salt) values ('sfleming7', 'aCrC2p', 'Sloan Fleming', 'sfleming7@moonfruit.com', 'KcbDobXfH7v4');
insert into [User] (Username, [Password], Name, Email, Salt) values ('bschettini8', 'KJGkKZ', 'Batholomew Schettini', 'bschettini8@wiley.com', 'cAEswbG8qkmY');
insert into [User] (Username, [Password], Name, Email, Salt) values ('lnutbeem9', 'snZMQY', 'Loralee Nutbeem', 'lnutbeem9@sina.com.cn', '9jRn6NYQJ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('amixa', 'HJ2dg0CzX', 'Arturo Mix', 'amixa@ted.com', 'htPKjY');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rkimblenb', '9P8XAKq', 'Rozella Kimblen', 'rkimblenb@icio.us', 'd3ppAuz');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rspickettc', 'DtuNK9z6', 'Ricardo Spickett', 'rspickettc@archive.org', 'FHGnxiRlH');
insert into [User] (Username, [Password], Name, Email, Salt) values ('chazelgreaved', 'ZbeL2kYqXsVy', 'Corrinne Hazelgreave', 'chazelgreaved@myspace.com', 'Xspx1jnL4n');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dpatkine', 'VXsSfHE2ERU', 'D''arcy Patkin', 'dpatkine@mapquest.com', 'CXoLJbd');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cwarwickf', 'HnnH53mhJ', 'Carree Warwick', 'cwarwickf@macromedia.com', 'JDhtzB8X1nv');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cgippg', 'RqYOjSfEafQ', 'Charita Gipp', 'cgippg@people.com.cn', 'Pd5e4S');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hdolmanh', 'Jo31hDr', 'Hadria Dolman', 'hdolmanh@ucla.edu', 'm1Oekvyfhc');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rbrusselli', 'NAvB9TzUaim', 'Rhea Brussell', 'rbrusselli@nih.gov', 'HkNTUCeIlSj');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dbonettj', 'Drvc8l3j2y6', 'Donny Bonett', 'dbonettj@dyndns.org', 'M9I75dv');
insert into [User] (Username, [Password], Name, Email, Salt) values ('joregank', 'FpjySuVv', 'Jolee O''Regan', 'joregank@booking.com', 'StVSNQ7o');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gstairsl', 'Vpml3cQ7', 'Giselbert Stairs', 'gstairsl@homestead.com', 'OrOuy5jHAv');
insert into [User] (Username, [Password], Name, Email, Salt) values ('breddochm', 'hxPGRJn2', 'Bonnee Reddoch', 'breddochm@printfriendly.com', '3gEak2jp');
insert into [User] (Username, [Password], Name, Email, Salt) values ('nbeethamn', 'izAW9lNY8C3', 'Nelie Beetham', 'nbeethamn@cam.ac.uk', 'S04d8FLdkVRG');
insert into [User] (Username, [Password], Name, Email, Salt) values ('chourstano', 'bIHugTCf2v', 'Cord Hourstan', 'chourstano@cornell.edu', 'diQTsTDoD');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dpollicattp', 'Kgl4I4bTYebQ', 'Darice Pollicatt', 'dpollicattp@nydailynews.com', 'aMV7k4F');
insert into [User] (Username, [Password], Name, Email, Salt) values ('wwimpq', 'TtnXlN7', 'Waylen Wimp', 'wwimpq@com.com', 'IKQWvxHUejJh');
insert into [User] (Username, [Password], Name, Email, Salt) values ('jdimontr', '1oXwBY6', 'Jandy Dimont', 'jdimontr@lulu.com', 'u9NQxJtorQ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ealessandruccis', 'K6r1IFgr3eO', 'Edgardo Alessandrucci', 'ealessandruccis@wix.com', 'bShgknUJjSc');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ttaaffet', '8rDWTl', 'Tanney Taaffe', 'ttaaffet@webnode.com', 'kEsVqKlmH');
insert into [User] (Username, [Password], Name, Email, Salt) values ('tcaltunu', 'sb8VbI4', 'Trenna Caltun', 'tcaltunu@chicagotribune.com', 'jRo2EzUNL8n');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hcraigsv', 'a21I8HU', 'Henrietta Craigs', 'hcraigsv@imgur.com', 'oFJ4q3474Th');
insert into [User] (Username, [Password], Name, Email, Salt) values ('awythew', 'PkWfUE', 'Andrey Wythe', 'awythew@parallels.com', 'odmiQNwC0');
insert into [User] (Username, [Password], Name, Email, Salt) values ('loldnallx', '1lzfipRRlQ', 'Lee Oldnall', 'loldnallx@google.com.hk', 'Zj3eGlfwg');
insert into [User] (Username, [Password], Name, Email, Salt) values ('nbusseyy', 'QEjz3S', 'Nicola Bussey', 'nbusseyy@flavors.me', 'elG2j9EPAA');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hbenjefieldz', 'whjSHp', 'Herculie Benjefield', 'hbenjefieldz@digg.com', 'lu2qt3');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ajimson10', 'hC4tByZ', 'Aguie Jimson', 'ajimson10@paypal.com', 'lgeExF');
insert into [User] (Username, [Password], Name, Email, Salt) values ('aduffree11', 'fvl4L0B', 'Abagael Duffree', 'aduffree11@soundcloud.com', 'BFCh6w5');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cluno12', 'h7vyGj8DuP', 'Claiborne Luno', 'cluno12@engadget.com', '2CDnYuAJI');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dbakewell13', 'B7IdM3', 'Dermot Bakewell', 'dbakewell13@stanford.edu', 'h4wv8ztqco');
insert into [User] (Username, [Password], Name, Email, Salt) values ('adebney14', 'OzrU3JK', 'Ardine Debney', 'adebney14@fc2.com', 'hcD5s0j7d98d');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cwille15', 'aM6zPdS0G', 'Claus Wille', 'cwille15@jugem.jp', 'uT5yP5enF1');
insert into [User] (Username, [Password], Name, Email, Salt) values ('pranger16', 'v4gHDS', 'Pauly Ranger', 'pranger16@i2i.jp', '3CqrDZsSVJ6G');
insert into [User] (Username, [Password], Name, Email, Salt) values ('bdadamo17', 'IBGsBkrC', 'Bank D''Adamo', 'bdadamo17@tripadvisor.com', '03Yj21tzsIN');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ctort18', 'Ttvqq2bcx4Y2', 'Cazzie Tort', 'ctort18@alexa.com', 'C4fJTpR');
insert into [User] (Username, [Password], Name, Email, Salt) values ('eroycroft19', 'T5aWyMPu64EU', 'Evanne Roycroft', 'eroycroft19@pcworld.com', 'MqaRzYH8bTwi');
insert into [User] (Username, [Password], Name, Email, Salt) values ('qpeevor1a', '0qUW2y5w', 'Quinlan Peevor', 'qpeevor1a@blog.com', 'NfqCRxsY1h');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gphelit1b', 'b0bdAJ4', 'Gibb Phelit', 'gphelit1b@cisco.com', 'Gk3lqpSDuBO');
insert into [User] (Username, [Password], Name, Email, Salt) values ('tgowdy1c', 'isUD1iEfWvW', 'Tabbie Gowdy', 'tgowdy1c@cbsnews.com', 'y9IpKLCIr');
insert into [User] (Username, [Password], Name, Email, Salt) values ('stitterton1d', 'tKWjM9PnJ', 'Syd Titterton', 'stitterton1d@cnn.com', 'NhvebFri');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rlower1e', 'D8FVro7A', 'Randene Lower', 'rlower1e@php.net', 'iqX92ewN');
insert into [User] (Username, [Password], Name, Email, Salt) values ('atackell1f', 'xPGMf8', 'Adah Tackell', 'atackell1f@lulu.com', 'W1j0t0aE');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cplastow1g', 'FfQg3oveX', 'Carie Plastow', 'cplastow1g@amazonaws.com', 'h2wjaDwNA');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gleaf1h', 'TDJa5p', 'Gardiner Leaf', 'gleaf1h@biglobe.ne.jp', 'T0s2Gh4');
insert into [User] (Username, [Password], Name, Email, Salt) values ('vfarny1i', 'K9jDAm', 'Valencia Farny', 'vfarny1i@cbslocal.com', '65IEeQ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('geschelle1j', 'TR6JKshn', 'Gertrud Eschelle', 'geschelle1j@vistaprint.com', '6kiVpWOpv');
insert into [User] (Username, [Password], Name, Email, Salt) values ('vlangthorne1k', '768Hpdas', 'Vivianna Langthorne', 'vlangthorne1k@wisc.edu', 'cT3tM1cj');
insert into [User] (Username, [Password], Name, Email, Salt) values ('eyoud1l', 'pxmHMdwsL', 'Emmaline Youd', 'eyoud1l@accuweather.com', 'QjdjABzlfky');
insert into [User] (Username, [Password], Name, Email, Salt) values ('mderks1m', 'hQrGcD7yb', 'Maximo Derks', 'mderks1m@yahoo.com', 'MKWX2P');
insert into [User] (Username, [Password], Name, Email, Salt) values ('orappport1n', 'UxBk6KzmWv', 'Odele Rappport', 'orappport1n@china.com.cn', 'akbSmNdX');
insert into [User] (Username, [Password], Name, Email, Salt) values ('nmcwilliam1o', 'fOP6Az5', 'Natala McWilliam', 'nmcwilliam1o@bbc.co.uk', 'hNvisayafz');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gbreming1p', '9NqWz8KjEM', 'Geneva Breming', 'gbreming1p@si.edu', 'PWJNsmdBKbR');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rsargeant1q', 'mYkIFt', 'Rutledge Sargeant', 'rsargeant1q@zdnet.com', 'PsvI29L6bCbT');
insert into [User] (Username, [Password], Name, Email, Salt) values ('aridwood1r', 'Tv8r5y', 'Alina Ridwood', 'aridwood1r@soundcloud.com', 'clzf0TfL5G');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hstanmore1s', 'SzrVaLSc', 'Haze Stanmore', 'hstanmore1s@acquirethisname.com', 'z3dh6ec3X88n');
insert into [User] (Username, [Password], Name, Email, Salt) values ('jtydeman1t', 'Lv7O6aZuh', 'Julianne Tydeman', 'jtydeman1t@fema.gov', 'QhZirt');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hkimberly1u', 'WW0jsWW23', 'Halsy Kimberly', 'hkimberly1u@bing.com', 'x2IWmTX7jsZb');
insert into [User] (Username, [Password], Name, Email, Salt) values ('baspray1v', 'DQrL8DFOR', 'Brennan Aspray', 'baspray1v@vk.com', 'VbYawueDfKqY');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cclitheroe1w', 'fpniDiKL7', 'Consalve Clitheroe', 'cclitheroe1w@google.com.br', 'QyZf1BI0');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ccurnnok1x', 'ZLDZpom32U', 'Cathy Curnnok', 'ccurnnok1x@fda.gov', 'Ithn5G5NAz');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cwhitsun1y', '7xPfKT5Rofxj', 'Cammy Whitsun', 'cwhitsun1y@xing.com', 'oPsE1hYYcY2D');
insert into [User] (Username, [Password], Name, Email, Salt) values ('sguyonneau1z', '36fboyuLCVW', 'Si Guyonneau', 'sguyonneau1z@noaa.gov', '8wzUxX50bOd');
insert into [User] (Username, [Password], Name, Email, Salt) values ('kgland20', '54ExvXf', 'Kellen Gland', 'kgland20@eventbrite.com', '1EOfGRcDt');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rcowpe21', 'xf0RlhTjARck', 'Rob Cowpe', 'rcowpe21@elpais.com', 'sJnHaQAZ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gisacke22', 'TR9wdA1SRh', 'Granger Isacke', 'gisacke22@yellowpages.com', 'gwncpRFDxw');
insert into [User] (Username, [Password], Name, Email, Salt) values ('egergler23', 'hBDbsp1B1', 'Emiline Gergler', 'egergler23@umn.edu', 'oW1XY8');
insert into [User] (Username, [Password], Name, Email, Salt) values ('jjumonet24', 'XX48f3mbEk', 'Juieta Jumonet', 'jjumonet24@cam.ac.uk', 'EyRk0db8PO');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hmatteini25', 'mShi0HQGK', 'Hilda Matteini', 'hmatteini25@cbc.ca', 'RZ7PkSSE');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dlindenboim26', 'EOl2Q85b', 'Doloritas Lindenboim', 'dlindenboim26@economist.com', 'gxJifymYIBN');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dmottram27', 'Xs4F8Ld2U', 'Douglas Mottram', 'dmottram27@de.vu', 'pPIq0UuE');
insert into [User] (Username, [Password], Name, Email, Salt) values ('shillan28', 'sV6plAxbGU', 'Susette Hillan', 'shillan28@elegantthemes.com', 'pFndGTXE');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rwichard29', 'SCgtC2', 'Ralf Wichard', 'rwichard29@hubpages.com', 'YBgA5GyT0kJ');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gjanz2a', 'kGNyAnZM9', 'Gillie Janz', 'gjanz2a@yale.edu', 'Qu4yHLYDByGa');
insert into [User] (Username, [Password], Name, Email, Salt) values ('aabelovitz2b', 'UUAVlmGU', 'Arlene Abelovitz', 'aabelovitz2b@eepurl.com', 'afKCyflE');
insert into [User] (Username, [Password], Name, Email, Salt) values ('vdoelle2c', 'DygUOZk', 'Velvet Doelle', 'vdoelle2c@youku.com', 'fO2NFRRP0uv8');
insert into [User] (Username, [Password], Name, Email, Salt) values ('rlorkings2d', 'zBsFM5KMmzXv', 'Robenia Lorkings', 'rlorkings2d@ed.gov', 'a1rImE');
insert into [User] (Username, [Password], Name, Email, Salt) values ('bcopello2e', 'icrhkYm', 'Bondon Copello', 'bcopello2e@360.cn', 'PeK2ukhiBO');
insert into [User] (Username, [Password], Name, Email, Salt) values ('hle2f', 'FKvD1gg80X27', 'Hannis Le feaver', 'hle2f@ca.gov', 'GtROZNjF');
insert into [User] (Username, [Password], Name, Email, Salt) values ('sphilbrook2g', '7B1EjuH', 'Simonne Philbrook', 'sphilbrook2g@discuz.net', 'DYf6PmGJkAK');
insert into [User] (Username, [Password], Name, Email, Salt) values ('mbarbary2h', 'E1OWLR26XW', 'Miquela Barbary', 'mbarbary2h@boston.com', '4hOAsd');
insert into [User] (Username, [Password], Name, Email, Salt) values ('cliddy2i', 'MLMC20LP6', 'Cammie Liddy', 'cliddy2i@ehow.com', 'mkbugGC');
insert into [User] (Username, [Password], Name, Email, Salt) values ('bvallentin2j', 'ZFgPuMxid', 'Benjie Vallentin', 'bvallentin2j@google.ru', 'Sg6yNk7x2b');
insert into [User] (Username, [Password], Name, Email, Salt) values ('syukhnevich2k', 'pGW5R3Ez4aLX', 'Sherwood Yukhnevich', 'syukhnevich2k@unicef.org', 'PQU2KoLy8T');
insert into [User] (Username, [Password], Name, Email, Salt) values ('ralsford2l', 'llIMIKsJkBU', 'Ruthanne Alsford', 'ralsford2l@alexa.com', 'Tdg5kSYN');
insert into [User] (Username, [Password], Name, Email, Salt) values ('mpetric2m', '2rMYPud', 'Maddie Petric', 'mpetric2m@who.int', 'b9cc4eL');
insert into [User] (Username, [Password], Name, Email, Salt) values ('pscruton2n', 'rhnlgc', 'Petronilla Scruton', 'pscruton2n@moonfruit.com', '1iNbcf');
insert into [User] (Username, [Password], Name, Email, Salt) values ('icarbert2o', 'FVLq4U', 'Iolande Carbert', 'icarbert2o@eventbrite.com', 'yGhAW3');
insert into [User] (Username, [Password], Name, Email, Salt) values ('jhawkin2p', '9sq9kDs', 'Jorgan Hawkin', 'jhawkin2p@independent.co.uk', 'ixHuKcpy');
insert into [User] (Username, [Password], Name, Email, Salt) values ('gsore2q', 'MSGg4x7vc', 'Guillermo Sore', 'gsore2q@weebly.com', 'HQDUBRR');
insert into [User] (Username, [Password], Name, Email, Salt) values ('dpauncefort2r', 'XSDCwDduI8H3', 'Dre Pauncefort', 'dpauncefort2r@miitbeian.gov.cn', 'WcIdTFJ8Qy');

insert into [User] (Username, [Password], Name, Email, Salt) values ('admin', 'admin', 'Dre Pauncefort', 'dpauncefort2r@miitbeian.gov.cn', 'WcIdTFJ8Qy');



CREATE TABLE Book (
	Id INT IDENTITY,
	Title VARCHAR(50),
	Author VARCHAR(50),
	[Description] Text
);
insert into Book (Title, Author, [Description]) values ('Freeway', 'Rosmunda Tallman', 'Periumbilic abdominal rigidity');
insert into Book (Title, Author, [Description]) values ('3 Days to Kill', 'Roosevelt Curnow', 'External constriction of unspecified part of neck, sequela');
insert into Book (Title, Author, [Description]) values ('Stars and Bars', 'Malynda Mowsdale', 'Laceration of superfic vn at shldr/up arm, unsp arm, init');
insert into Book (Title, Author, [Description]) values ('Shanghai Gesture, The', 'Ernst Spragg', 'Drowning and submersion due to unsp watercraft sinking, subs');
insert into Book (Title, Author, [Description]) values ('American Teen', 'Harrie Dollar', 'Driver of pk-up/van injured in clsn w hv veh in traf, init');
insert into Book (Title, Author, [Description]) values ('I Think I Do', 'Marne Gallatly', 'Pedl cyc driver inj in clsn w rail trn/veh nontraf, sequela');
insert into Book (Title, Author, [Description]) values ('When a Woman Ascends the Stairs (Onna ga kaidan wo agaru toki)', 'Elysha Linnock', 'Psychotropic drugs');
insert into Book (Title, Author, [Description]) values ('99 River Street', 'Shellie Collingworth', 'Legal intervnt involving unsp sharp objects, suspect injured');
insert into Book (Title, Author, [Description]) values ('Carnival of Souls', 'Town Bandiera', 'Gallstone ileus');
insert into Book (Title, Author, [Description]) values ('Hey Arnold! The Movie', 'Vergil Bellanger', 'Myopathy due to other toxic agents');
insert into Book (Title, Author, [Description]) values ('Secret Life of Zoey, The', 'Sallie Scarbarrow', 'Displaced trimalleol fx r low leg, init for opn fx type I/2');
insert into Book (Title, Author, [Description]) values ('Rebel Without a Cause', 'Kin Karus', 'Poisoning by keratolyt/keratplst/hair trmt drug, undet');
insert into Book (Title, Author, [Description]) values ('Barbary Coast', 'Jerome Rentenbeck', 'Nondisp transverse fx shaft of l ulna, 7thH');
insert into Book (Title, Author, [Description]) values ('Diary for Timothy, A', 'Constanta Grisewood', 'Adverse effect of inhaled anesthetics, initial encounter');
insert into Book (Title, Author, [Description]) values ('Pandaemonium', 'Benson Gatenby', 'Disruption of wound, unspecified, subsequent encounter');
insert into Book (Title, Author, [Description]) values ('Hunters, The', 'Nappy Bingall', 'Fall into empty swimming pool, subsequent encounter');
insert into Book (Title, Author, [Description]) values ('There''s Something Wrong with Aunt Diane', 'Keefer Hodcroft', 'Osteopathy in diseases classified elsewhere, unsp forearm');
insert into Book (Title, Author, [Description]) values ('Almost Married', 'Susanna Kull', 'Unspecified subluxation of left knee, initial encounter');
insert into Book (Title, Author, [Description]) values ('Disco Pigs', 'Merridie Eringey', 'Laceration w/o fb of left great toe w/o damage to nail, init');
insert into Book (Title, Author, [Description]) values ('Niagara', 'Chloris Congreave', 'Other reactive arthropathies, left knee');
insert into Book (Title, Author, [Description]) values ('Man in the Moon, The', 'Ethelred Petrolli', 'Angioimmunoblastic T-cell lymphoma');
insert into Book (Title, Author, [Description]) values ('Jolly Boys'' Last Stand, The', 'Stanford Bleakman', 'Plasmodium vivax malaria with rupture of spleen');
insert into Book (Title, Author, [Description]) values ('I Am Legend', 'Jany Leonard', 'Pnctr w foreign body of thmb w/o damage to nail, sequela');
insert into Book (Title, Author, [Description]) values ('Yankee Zulu', 'Lark Broggio', 'Other contact with sea lion, subsequent encounter');
insert into Book (Title, Author, [Description]) values ('Love is Eternal While It Lasts', 'Augusta Bonsul', 'Complete traumatic trnsphal amputation of l mid finger, subs');
insert into Book (Title, Author, [Description]) values ('Nine Lives', 'Midge Dankersley', 'Local-rel symptc epi w simple partial seiz, not ntrct');
insert into Book (Title, Author, [Description]) values ('The Boy', 'Jessika Codner', 'Oth place in school dormitory as place');
insert into Book (Title, Author, [Description]) values ('Long Day Closes, The', 'Karita Meeking', 'Progressive external ophthalmoplegia, left eye');
insert into Book (Title, Author, [Description]) values ('Zero', 'Luise Delicate', 'Bennett''s fracture, left hand, sequela');
insert into Book (Title, Author, [Description]) values ('Miracle at Oxford (True Blue)', 'Kellen Knowlden', 'Disp fx of distal phalanx of right thumb, init for opn fx');
insert into Book (Title, Author, [Description]) values ('A Good Marriage', 'Linet Di Giorgio', 'Alcohol-induced pseudo-Cushing''s syndrome');
insert into Book (Title, Author, [Description]) values ('Musicwood', 'Elli Edmands', 'Pathological fracture, right ulna, subs for fx w malunion');
insert into Book (Title, Author, [Description]) values ('Catching Hell', 'Herschel Alberts', 'Unsp fx low end r tibia, subs for opn fx type I/2 w nonunion');
insert into Book (Title, Author, [Description]) values ('Hotel for Dogs', 'Nixie Behneke', 'Displacement of other urinary stents, initial encounter');
insert into Book (Title, Author, [Description]) values ('Mexican, The', 'Lindsay Esche', 'Other female genital prolapse');
insert into Book (Title, Author, [Description]) values ('R.I.P.D.', 'Berta Coan', 'Nondisp simp suprcndl fx w/o intrcndl fx unsp humer, 7thB');
insert into Book (Title, Author, [Description]) values ('Virtual JFK: Vietnam If Kennedy Had Lived', 'Clarine Farrall', 'Malignant neoplasm of left orbit');
insert into Book (Title, Author, [Description]) values ('Home Movie', 'Gibb Windrus', 'Gastroduodenitis, unspecified, with bleeding');
insert into Book (Title, Author, [Description]) values ('Attack Force Z (a.k.a. The Z Men) (Z-tzu te kung tui)', 'Shina Cruft', 'Laceration w/o fb of l idx fngr w damage to nail, subs');
insert into Book (Title, Author, [Description]) values ('Story of Maths, The', 'Philip Craxford', 'Displaced fracture of base of neck of unspecified femur');
insert into Book (Title, Author, [Description]) values ('Yanks', 'Grady Massow', 'Dining room in school dormitory as place');
insert into Book (Title, Author, [Description]) values ('Dark Alibi', 'Wanids Lumbly', 'Foliclar lymphoma grade IIIb, nodes of axilla and upper limb');
insert into Book (Title, Author, [Description]) values ('Suez', 'Millard Bateman', 'Fall on board canoe or kayak, sequela');
insert into Book (Title, Author, [Description]) values ('Donnie Brasco', 'Susanetta Billion', 'Burn of second degree of wrist');
insert into Book (Title, Author, [Description]) values ('Something Wicked This Way Comes', 'Garrek Sokale', 'Disp fx of med phalanx of l less toe(s), 7thG');
insert into Book (Title, Author, [Description]) values ('Ricky & Barabba', 'Obidiah Dicte', 'Encntr for care and exam of mother immediately after del');
insert into Book (Title, Author, [Description]) values ('Slacker', 'Jannel Holberry', 'Poisoning by antiasthmatics, intentional self-harm, init');
insert into Book (Title, Author, [Description]) values ('Liebelei', 'Truman Slidders', 'Internal hirudiniasis');
insert into Book (Title, Author, [Description]) values ('Cliffhanger', 'Claudianus Bulch', 'Injury of internal jugular vein');
insert into Book (Title, Author, [Description]) values ('East, The', 'Reynard Boxall', 'Mechanical ptosis of eyelid');
insert into Book (Title, Author, [Description]) values ('Crossroads', 'Carol Dowty', 'Gonococcal infection of musculoskeletal system, unspecified');
insert into Book (Title, Author, [Description]) values ('We All Loved Each Other So Much (C''eravamo tanto amati)', 'Samara Blackborn', 'Displaced fracture of pisiform, left wrist, sequela');
insert into Book (Title, Author, [Description]) values ('Kings of the Sun', 'Northrup Thorogood', 'Displ transverse fx shaft of unsp rad, 7thN');
insert into Book (Title, Author, [Description]) values ('Jungle Fighters', 'Ema Eltun', 'Infect/inflm reaction due to unsp int joint prosth, subs');
insert into Book (Title, Author, [Description]) values ('One Husband Too Many', 'Denver Paolone', 'Streptococcus B carrier state compl preg/chldbrth');
insert into Book (Title, Author, [Description]) values ('Bummer (Bumer)', 'Padriac Pattison', 'Fracture of unsp phalanx of unsp thumb, init for clos fx');
insert into Book (Title, Author, [Description]) values ('Spice World', 'Arleta Matzkaitis', 'Pre-exist hyp heart and chr kidney disease comp the puerp');
insert into Book (Title, Author, [Description]) values ('Three Wishes', 'Quentin Silverson', 'Traumatic cerebral edema w LOC of 30 minutes or less, subs');
insert into Book (Title, Author, [Description]) values ('Before the Rain (Pred dozhdot)', 'Gradeigh Deniscke', 'Endo, nutritional and metabolic diseases compl preg/chldbrth');
insert into Book (Title, Author, [Description]) values ('The Fox and the Hare', 'Frankie Spottiswood', 'Toxic effect of lacrimogenic gas, undetermined');
insert into Book (Title, Author, [Description]) values ('Divorce', 'Bendick Grimm', 'Other burn on board fishing boat, subsequent encounter');
insert into Book (Title, Author, [Description]) values ('Smilla''s Sense of Snow', 'Jasmin McOnie', 'Nondisp fx of med malleolus of unsp tibia, 7thM');
insert into Book (Title, Author, [Description]) values ('Beyond Re-Animator', 'Kirby McCue', 'Insect bite (nonvenomous) of breast, right breast, subs');
insert into Book (Title, Author, [Description]) values ('Sexual Dependency (Dependencia sexual)', 'Elsa Huntall', 'Superficial frostbite of neck');
insert into Book (Title, Author, [Description]) values ('Goddess, The', 'Staffard Cleaton', 'Adhes due to fb acc left in body fol surgical op, subs');
insert into Book (Title, Author, [Description]) values ('Our Daily Bread (Unser täglich Brot)', 'Zacharie Lomansey', 'Underdosing of anticoagulants, subsequent encounter');
insert into Book (Title, Author, [Description]) values ('The Time of Their Lives', 'Maxim Ryott', 'Unspecified injury of popliteal vein, left leg');
insert into Book (Title, Author, [Description]) values ('Escapist, The', 'Maren Kitt', 'Toxic effect of cntct w venom marine plant, slf-hrm, sequela');
insert into Book (Title, Author, [Description]) values ('My Big Fat Greek Wedding', 'Mar Shippam', 'Drowning and submersion due to fall off passenger ship, init');
insert into Book (Title, Author, [Description]) values ('Fiorile', 'Cleopatra Glusby', 'Unspecified fracture of sacrum, sequela');
insert into Book (Title, Author, [Description]) values ('Acts of Worship ', 'Ryley Hanssmann', 'Benign neoplasm of bone and articular cartilage');
insert into Book (Title, Author, [Description]) values ('Conviction', 'Marchall Bathow', 'Disp fx of olecran pro w/o intartic extn unsp ulna, 7thC');
insert into Book (Title, Author, [Description]) values ('Bal (Honey)', 'Ebeneser Anthony', 'Chronic embolism and thrombosis of unspecified femoral vein');
insert into Book (Title, Author, [Description]) values ('Miss Castaway and the Island Girls', 'Enrichetta Spain-Gower', 'Nondisp fx of glenoid cavity of scapula, left shoulder');
insert into Book (Title, Author, [Description]) values ('Diplomacy (Diplomatie)', 'Merna Mazzey', 'Oth coma,w/o Glasgow coma scale score,or w/part score report');
insert into Book (Title, Author, [Description]) values ('Trouble at Timpetill (Enfants de Timpelbach, Les)', 'Clio Leal', 'Corrosion of third degree of right lower leg');
insert into Book (Title, Author, [Description]) values ('Point Men, The', 'Osborn Peabody', 'Laceration without foreign body, left thigh, init encntr');
insert into Book (Title, Author, [Description]) values ('Merrill''s Marauders', 'Padgett Heskey', 'Breakdown of other nervous sys device, implant or graft');
insert into Book (Title, Author, [Description]) values ('Naked Fear', 'Ursuline Yallop', 'Other subluxation of right wrist and hand, initial encounter');
insert into Book (Title, Author, [Description]) values ('Total Recall', 'Antonin Gonsalvez', 'Postproc hematoma of skin, subcu following other procedure');
insert into Book (Title, Author, [Description]) values ('Black Moon', 'Worden Pieterick', 'Fx unsp phalanx of r idx fngr, subs for fx w routn heal');
insert into Book (Title, Author, [Description]) values ('Macabre', 'Vanny Ambage', 'Type III occipital condyle fracture, unsp side, sequela');
insert into Book (Title, Author, [Description]) values ('Ice Poison', 'Debi Ivatts', 'Bimalleolar fracture of lower leg');
insert into Book (Title, Author, [Description]) values ('Makai Tensho: Samurai Reincarnation (Makai tenshô)', 'Delmore Cordet', 'Nondisp fx of unsp radial styloid pro, 7thP');
insert into Book (Title, Author, [Description]) values ('Glass-blower''s Children, The (Glasblåsarns barn)', 'Chelsy Durber', 'Other ectopic pregnancy with intrauterine pregnancy');
insert into Book (Title, Author, [Description]) values ('Jingle All the Way 2', 'Jase Greaser', 'Female genital tract-skin fistulae');
insert into Book (Title, Author, [Description]) values ('Lorenzo''s Oil', 'Gerick Windybank', 'Disp fx of r radial styloid pro, subs for clos fx w malunion');
insert into Book (Title, Author, [Description]) values ('Fortune, The', 'Fredi Langdridge', 'Unsp fracture of left femur, subs for clos fx w nonunion');
insert into Book (Title, Author, [Description]) values ('Shepard & Dark', 'Marylou McGrale', 'Other bursal cyst, unspecified shoulder');
insert into Book (Title, Author, [Description]) values ('Shadow Magic', 'Anatol Downse', 'Fracture of orbital floor, right side');
insert into Book (Title, Author, [Description]) values ('Black Tights (1-2-3-4 ou Les Collants noirs)', 'Andriette Wallbutton', 'Epidur hemor w LOC w death due to oth causes bf consc, init');
insert into Book (Title, Author, [Description]) values ('Laggies', 'Cristy Adamson', 'Other specified injury of blood vessel of left index finger');
insert into Book (Title, Author, [Description]) values ('Unzipped', 'Cornall Dishman', 'Sltr-haris Type I physl fx low end l femr, 7thD');
insert into Book (Title, Author, [Description]) values ('On Deadly Ground', 'Stepha Ewestace', 'Nondisp suprcndl fx w intrcndl extn low end r femr, 7thR');
insert into Book (Title, Author, [Description]) values ('Anniversary, The', 'Bertram Tithecott', 'Obstructed labor due to malpos and malpresent, unsp, fetus 2');
insert into Book (Title, Author, [Description]) values ('Heart of America', 'Yolande Moens', 'Postdysenteric arthropathy, shoulder');
insert into Book (Title, Author, [Description]) values ('New Wave, A', 'Luci Aleksashin', 'Traum rupture of ligament of r little finger at MCP/IP jt');
insert into Book (Title, Author, [Description]) values ('Charge of the Light Brigade, The', 'Morgen Ivory', 'Maternal care for damage to fetus from alcohol, fetus 3');
insert into Book (Title, Author, [Description]) values ('Heart of America', 'Mack Lemerie', 'Toxic effect of contact w oth venomous fish, undet, init');
insert into Book (Title, Author, [Description]) values ('Light Sleeper', 'Mordecai Monro', 'Disp fx of neck of first metacarpal bone, right hand, init');



CREATE TABLE Library (
	Id INT IDENTITY,
	Name VARCHAR(50),
	Location VARCHAR(50)
);
insert into Library (Name, Location) values ('Kwilith', '1679 Sauthoff Road');
insert into Library (Name, Location) values ('Skinte', '0037 Red Cloud Drive');
insert into Library (Name, Location) values ('Devify', '40600 Duke Pass');
insert into Library (Name, Location) values ('Browsedrive', '6 Aberg Drive');
insert into Library (Name, Location) values ('Oozz', '394 Mallard Avenue');
insert into Library (Name, Location) values ('Browsecat', '2408 Colorado Road');
insert into Library (Name, Location) values ('Feednation', '60111 Delladonna Terrace');
insert into Library (Name, Location) values ('Mybuzz', '140 Lindbergh Avenue');
insert into Library (Name, Location) values ('Dabtype', '7 North Crossing');
insert into Library (Name, Location) values ('Photobug', '7719 Katie Drive');
insert into Library (Name, Location) values ('Youspan', '86 American Ash Lane');
insert into Library (Name, Location) values ('Skyba', '1 Farragut Lane');
insert into Library (Name, Location) values ('Lazz', '9 Quincy Park');
insert into Library (Name, Location) values ('Buzzster', '5900 Stang Place');
insert into Library (Name, Location) values ('Shuffletag', '8828 Chive Plaza');
insert into Library (Name, Location) values ('Buzzbean', '0 Dottie Center');
insert into Library (Name, Location) values ('Twiyo', '5035 Schiller Terrace');
insert into Library (Name, Location) values ('Gevee', '3840 Doe Crossing Road');
insert into Library (Name, Location) values ('Twimbo', '29 Sommers Street');
insert into Library (Name, Location) values ('Trudeo', '1 Doe Crossing Plaza');
insert into Library (Name, Location) values ('Oyoyo', '5 Judy Street');
insert into Library (Name, Location) values ('Skyvu', '83 Tomscot Plaza');
insert into Library (Name, Location) values ('Jetpulse', '43390 Holmberg Terrace');
insert into Library (Name, Location) values ('Mynte', '1 Reindahl Park');
insert into Library (Name, Location) values ('Janyx', '1648 Shelley Parkway');
insert into Library (Name, Location) values ('Eimbee', '3089 Mitchell Center');
insert into Library (Name, Location) values ('Feedfish', '799 Dovetail Court');
insert into Library (Name, Location) values ('Avaveo', '40 Raven Drive');
insert into Library (Name, Location) values ('Skajo', '5 Mesta Hill');
insert into Library (Name, Location) values ('Fliptune', '444 Mosinee Center');
insert into Library (Name, Location) values ('Abatz', '654 Iowa Hill');
insert into Library (Name, Location) values ('Realbridge', '17841 Memorial Trail');
insert into Library (Name, Location) values ('Oodoo', '81691 East Court');
insert into Library (Name, Location) values ('Fatz', '7 Macpherson Crossing');
insert into Library (Name, Location) values ('Rhybox', '1 Erie Place');
insert into Library (Name, Location) values ('Kazu', '87604 Canary Crossing');
insert into Library (Name, Location) values ('Oyoba', '25 Homewood Lane');
insert into Library (Name, Location) values ('Fivespan', '210 Mendota Court');
insert into Library (Name, Location) values ('Mydo', '8 Dovetail Alley');
insert into Library (Name, Location) values ('Brightbean', '5272 Kim Place');
insert into Library (Name, Location) values ('Zoozzy', '86194 Mendota Plaza');
insert into Library (Name, Location) values ('Aivee', '9 Bobwhite Road');
insert into Library (Name, Location) values ('Pixope', '5619 Londonderry Place');
insert into Library (Name, Location) values ('Blogspan', '7360 Cherokee Crossing');
insert into Library (Name, Location) values ('Twiyo', '974 Northwestern Crossing');
insert into Library (Name, Location) values ('Aibox', '17341 Reinke Terrace');
insert into Library (Name, Location) values ('Rhyzio', '2702 Anderson Crossing');
insert into Library (Name, Location) values ('Livepath', '02597 Browning Lane');
insert into Library (Name, Location) values ('Riffpath', '998 Cody Hill');
insert into Library (Name, Location) values ('Skinix', '56 Vermont Alley');
insert into Library (Name, Location) values ('Photospace', '9 Brown Pass');
insert into Library (Name, Location) values ('Wordware', '254 Mesta Junction');
insert into Library (Name, Location) values ('Realbuzz', '4313 Fallview Point');
insert into Library (Name, Location) values ('Skilith', '9 Lindbergh Crossing');
insert into Library (Name, Location) values ('Topiczoom', '98365 Lindbergh Avenue');
insert into Library (Name, Location) values ('Devpulse', '7 Knutson Hill');
insert into Library (Name, Location) values ('Flashdog', '15 Moulton Park');
insert into Library (Name, Location) values ('Photofeed', '484 Parkside Park');
insert into Library (Name, Location) values ('Kwideo', '63414 Gateway Way');
insert into Library (Name, Location) values ('Rhycero', '625 Crest Line Court');
insert into Library (Name, Location) values ('Bluezoom', '84468 Golden Leaf Lane');
insert into Library (Name, Location) values ('Thoughtstorm', '352 Barnett Junction');
insert into Library (Name, Location) values ('Thoughtbridge', '64 Prairieview Plaza');
insert into Library (Name, Location) values ('Yodoo', '6461 Bluejay Court');
insert into Library (Name, Location) values ('Eimbee', '85703 Homewood Crossing');
insert into Library (Name, Location) values ('Yata', '2 Hansons Pass');
insert into Library (Name, Location) values ('Feedfish', '663 Ilene Plaza');
insert into Library (Name, Location) values ('Flipbug', '71 Nobel Circle');
insert into Library (Name, Location) values ('Yakijo', '385 Spohn Lane');
insert into Library (Name, Location) values ('Rooxo', '74344 Shelley Crossing');
insert into Library (Name, Location) values ('Vidoo', '660 Sloan Junction');
insert into Library (Name, Location) values ('Gabcube', '03 Messerschmidt Lane');
insert into Library (Name, Location) values ('Eayo', '904 Bayside Road');
insert into Library (Name, Location) values ('Riffpath', '1 Garrison Street');
insert into Library (Name, Location) values ('Kazu', '55635 Stephen Junction');
insert into Library (Name, Location) values ('Yabox', '412 Becker Hill');
insert into Library (Name, Location) values ('Feedspan', '4712 Nevada Lane');
insert into Library (Name, Location) values ('Wikizz', '650 Di Loreto Road');
insert into Library (Name, Location) values ('Topiclounge', '2455 Brentwood Plaza');
insert into Library (Name, Location) values ('Eare', '9 West Street');
insert into Library (Name, Location) values ('Fadeo', '24981 Oakridge Lane');
insert into Library (Name, Location) values ('Photobug', '2 Michigan Street');
insert into Library (Name, Location) values ('Bluejam', '869 Prentice Street');
insert into Library (Name, Location) values ('Devshare', '62 Cody Terrace');
insert into Library (Name, Location) values ('Skipfire', '6 Pond Way');
insert into Library (Name, Location) values ('Geba', '2486 Stephen Circle');
insert into Library (Name, Location) values ('Trunyx', '7897 Talmadge Avenue');
insert into Library (Name, Location) values ('Jatri', '69 Little Fleur Pass');
insert into Library (Name, Location) values ('Photobug', '768 Kinsman Parkway');
insert into Library (Name, Location) values ('Youbridge', '4 Amoth Center');
insert into Library (Name, Location) values ('Photobean', '0003 Hanson Parkway');
insert into Library (Name, Location) values ('Gigabox', '397 Farragut Circle');
insert into Library (Name, Location) values ('Trudeo', '401 Memorial Way');
insert into Library (Name, Location) values ('Omba', '703 Golden Leaf Circle');
insert into Library (Name, Location) values ('Zoomlounge', '313 Sloan Circle');
insert into Library (Name, Location) values ('Wikivu', '90380 Bartelt Trail');
insert into Library (Name, Location) values ('Dabshots', '445 Scott Court');
insert into Library (Name, Location) values ('Livefish', '9322 Luster Plaza');
insert into Library (Name, Location) values ('Bubblemix', '50 Dunning Lane');
insert into Library (Name, Location) values ('Eabox', '4343 Debra Junction');

INSERT INTO [User] (Username,[Passwor],Name,Email,Salt) VALUES('admin','admin','admin','admin@admin.com','admin')